### PR TITLE
fix syscall.Mprotect panic: permission denied

### PR DESCRIPTION
**Pull request by gbwllx**
macos vm_protect

### CODE REVIEW

**Comment by agiledragon** [comment]
https://github.com/eisenxp/macos-golink-wrapper
What do u think this solution?

**Comment by gbwllx** [comment]
> https://github.com/eisenxp/macos-golink-wrapper
> What do u think this solution?

sorry I didn't try it, but I thought it's not as convenient

**Comment by agiledragon** [comment]
First of all, it doesn't matter! 
Although this method is more convenient, it is intrusive to the code and too complicated, which makes the subsequent code difficult to maintain.
I will contact you individually and we will communicate further.

**Comment by agiledragon** [comment]
My WeChat ID is zhangxiaolong_cgo, please note gomonkey.

**Pull request closed without merging**
